name: Package addon

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Set GitHub oAuth env
        run: |
          echo "GITHUB_OAUTH=$GITHUB_TOKEN" >> $GITHUB_ENV

      - name: Add mask for oAuth token
        run: |
          echo "::add-mask::$GITHUB_OAUTH"

      - name: Create Retail Package
        uses: BigWigsMods/packager@master
        env:
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Create Classic Package
        uses: BigWigsMods/packager@master
        with:
          args: -g classic
        env:
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Create BCC Package
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc
        env:
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Send Status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
        if: always()